name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: docker compose build

  docker:
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin

    - name: Push Docker images
      run: |
        docker compose push

  deploy:
    runs-on: ubuntu-22.04
    needs: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clean up old resources
      run: |
        docker compose down --volumes --remove-orphans
        docker container prune -f
        docker volume prune -f

    - name: Deploy services
      run: docker compose up -d --build
